# Generated by Django 4.2.6 on 2023-11-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='course',
            field=models.CharField(default='default surname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='surname',
            field=models.CharField(default='default surname', max_length=100),
            preserve_default=False,
        ),
    ]
